"""add 3 new columns to components table

Revision ID: c5e866465cea
Revises: 0001
Create Date: 2026-08-12 15:15:14.494847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e866465cea'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('datasheet_url', sa.Text(), nullable=True))
    op.add_column('components', sa.Column('datasheet_summary', sa.Text(), nullable=True))
    op.add_column('components', sa.Column('qdrant_indexed', sa.Boolean(), nullable=True))
    op.alter_column('components', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('components', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('components', 'qdrant_indexed')
    op.drop_column('components', 'datasheet_summary')
    op.drop_column('components', 'datasheet_url')
    # ### end Alembic commands ###
